### ISSUE TITLE
How to override pre-compiled code with interpreted version?

### ISSUE THREAD

**Issue by theclapp** [traefik/yaegi#1024]
I'd like to be able to replace pre-compiled code with Yaegi-interpreted code.

So far the best I've come up with is something like this:

```go
// Given a type F
type F struct{}

// instead of this:
func (r F) Method() int { return 10 }

// do this:

// the method just calls a func variable
func (r F) Method() int { return y_F_Method(r) }

// the func variable has the actual method code
var y_F_Method = func(r F) int { return 10 }

// a helper function for setting y_F_Method
func SetMethod(f func(F) int) { y_F_Method = f }

// call it
fi := F{}
fmt.Println("fi.Method:", fi.Method()) // prints 10

// set up to use Yaegi
// Some code elided
i.Use(interp.Exports{
	"ymain": {
		"F":         reflect.ValueOf((*F)(nil)),
		"SetMethod": reflect.ValueOf(SetMethod),
	},
})

_, err := i.Eval(`import "ymain"`)
if err != nil {
	fmt.Println(err)
	return
}

fmt.Println("setting y_F_Method to return 20")
_, err = i.Eval(`ymain.SetMethod(func(_ ymain.F) int { return 20 })`)
if err != nil {
	fmt.Println(err)
	return
}

fmt.Println("fi.Method:", fi.Method()) // prints 20
```

Is there a better way?

**Comment by theclapp** [comment]
Here's the whole program:

```go
package main

import (
	"fmt"
	"reflect"

	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
	"github.com/traefik/yaegi/stdlib/unrestricted"
)

type F struct{}

func (r F) Method() int { return y_F_Method(r) }

var y_F_Method = func(r F) int { return 10 }

func SetMethod(f func(F) int) { y_F_Method = f }

func main() {
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)
	i.Use(unrestricted.Symbols)
	fmt.Println(reflect.TypeOf(F{}).PkgPath())

	fi := F{}
	fmt.Println("fi.Method:", fi.Method())

	i.Use(interp.Exports{
		"ymain": {
			"F":         reflect.ValueOf((*F)(nil)),
			"SetMethod": reflect.ValueOf(SetMethod),
		},
	})

	_, err := i.Eval(`import "ymain"`)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("setting y_F_Method to return 20")
	_, err = i.Eval(`ymain.SetMethod(func(_ ymain.F) int { return 20 })`)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("fi.Method:", fi.Method())

	fmt.Println("setting y_F_Method to return 30")
	v, err := i.Eval(`v := func(_ ymain.F) int { return 30 }; v`)
	if err != nil {
		fmt.Println(err)
		return
	}
	y_F_Method = v.Interface().(func(F) int)

	fmt.Println("fi.Method:", fi.Method())
}
```

output:
```
fi.Method: 10
setting y_F_Method to return 20
fi.Method: 20
setting y_F_Method to return 30
fi.Method: 30
```

**Comment by mpl** [comment]
That's an interesting exercice, but I'm not sure how to answer your question without knowing the constraints.

Here's my suspicion: in theory, your code would just be something like:

```
type F struct{}

func (r F) Method() int { blabla }
```

and there would be no business with ```y_F_Method```. And I'm guessing what you would like to do is to override the body of Method() in the simplest way possible. You had to invent this scheme of using  ```y_F_Method``` as the body of Method because that's what you came up as the way to override the body of Method? Am I guessing correctly, or do you actually want to have this ```y_F_Method ``` intermediate ?

Let me know if it's the former and we'll see if we can think of something else. Otherwise, if it's the latter, is there anything you don't like about the way you've done it? Why are you asking if there's another way?

**Comment by theclapp** [comment]
Thank you for your answer!

You are guessing correctly: what I would like to do is to override the body of Method() in the simplest way possible, and that's what I came up with.  I'd be happy to skip the part about `y_F_Method`.

> is there anything you don't like about the way you've done it? Why are you asking if there's another way?

It does seem kind of clunky, and I figured that obviously y'all know Yaegi (and probably the deep dark nuts and bolts of the Go spec) better than I do, and I hoped you'd say something like "Oh you can just redeclare it directly!":

```go
i.Eval(`
package main
func (r F) Method() int { return 20 }
`)
```

and it'd somehow magically work.

> In any case, kudos for what you've done so far, it's pretty creative.

Thanks!

You ain't seen nothin' yet.  ("He said modestly", haha.)  I'm working on code to use this idea and Yaegi to do hot-reloading on live code at the function/method level.  It's going well so far.  :)

Thanks again for your time!

**Comment by mpl** [comment]
@theclapp 

1) At the moment, we don't think there's any way to do what you want to do in a more direct way.

2) But more importantly, we do not think Yaegi should allow you to do that as, if you think about it, the equivalent is actually not allowed in pure Go. e.g. if you have:

```
package foo

type T struct{}

func (t T) Bar() { blabla }
```

then it is not allowed in any program that imports foo, to redefine/override foo.T.Bar itself. Except by implementing hooks or such techniques that allow you to redefine the body of Bar, similarly to what you have done yourself.

**Comment by theclapp** [comment]
> At the moment, we don't think there's any way to do what you want to do in a more direct way.

👍 

> But more importantly, we do not think Yaegi should allow you to do that as, if you think about it, the equivalent is actually not allowed in pure Go

Sure, that's fine.  I was just checking.

Thanks again!
