### ISSUE TITLE
Send existing stacktrace from paniced Eval to the configured interp.Options.Stderr

### ISSUE THREAD

**Issue by TheMightyGit** [traefik/yaegi#1030]
#### Proposal

At the moment (0.9.11) the stacktrace when an Eval panics goes only to the apps `fmt.Println()` and not to the configured `interp.Options.Stderr`. This makes it hard to capture the stack trace when you wish to surface that info to somewhere other than the apps stdout.

If yaegi also printed the stacktrace to the configured `interp.Options.Stderr` it would make it possible for me to consume it, and logically it makes sense to me that the stacktrace would appear in the scripts configured Stderr.

I believe this is the line that prints it - https://github.com/traefik/yaegi/blob/master/interp/run.go#L182 

#### Background

I `recover()` from Eval panics and wish to show the existing stacktrace (that only seems to go to the apps stdout) to the user in the GUI.

#### Workarounds

I could not find one, but maybe I missed another way of getting the stacktrace from a panic'ed eval?

I am also compiling for JS/WASM where os.Pipe() is not available, so I cannot simply replace and consume main apps Stdout/err to get the stacktrace when the Eval panics.

**Comment by tigerwill90** [comment]
I think `fmt.Println()` is here only for testing purpose according to https://github.com/traefik/yaegi/blob/master/interp/interp.go#L210
