### ISSUE TITLE
Extract unsafe, failed formatting source. expected ; found -

### ISSUE THREAD

**Issue by ShadowNight573** [traefik/yaegi#1059]
I've been trying to get the unsafe package to be available but this happens every time I try to extract it. I have no idea where to go from here. Any ideas?
![EB0A28FC-9131-4C3D-A9FB-F024555BCD3C](https://user-images.githubusercontent.com/56423789/111791601-5dc8ac80-8891-11eb-9d29-9d89f1f40058.jpeg)

**Comment by mvertes** [comment]
Hello @ShadowNight573,

The standard library `unsafe` package is a special case, it  can not be processed entirely by the extract command, and some symbols must be re-implememented at yaegi level (planned but not completed yet). Furthermore, you should not need to extract it yourself, as the available symbols are already made available using `-unsafe` flag.

**Comment by ShadowNight573** [comment]
Sorry its taken me so long to respond back, I appreciate your answer but I don't exactly know how to implement the -unsafe flag because I am running the code through `go run main.go` and then importing the interpretation packages into my project.

I ran accross this issue whenever I tried to use a package inside the code I was evaluating... could you explain further? @mvertes
