### ISSUE TITLE
Feature: add Offsetof to unsafe

### ISSUE THREAD

**Issue by For-ACGN** [traefik/yaegi#1062]
#### Proposal
I want to add unsafe.Offsetof, can you help me? @nrwiersma

```go
func offsetof(s interface{}, f string) uintptr {
	typ := reflect.ValueOf(s).Type()
	sf, ok := typ.FieldByName(f)
	if !ok {
		panic(fmt.Sprintf("structure %s not contain field: \"%s\"", typ, f))
	}
	return sf.Offset
}
```

This code can get structure field offset, but I don't know how to add it to the yaegi interpreter,
for use like
```go
unsafe.Offsetof(StructureA{}.FieldA)
```

I can only add a simple api but with two parameter, offset(s interface{}, f string) to "stdlib/unsafe".
#### Background
unsafe.Offsetof

#### Workarounds
unsafe.Offsetof

**Comment by mvertes** [comment]
The `typ` parameter to `unsafe.OffsetOf(typ interface{})` must be derived from a struct field selector expression, which is done internally in `yaegi` by the parser. I will handle this, as there is not a proper way to implement it separately.
