### ISSUE TITLE
Question: how do I make "unsafe" available?

### ISSUE THREAD

**Issue by ShadowNight573** [traefik/yaegi#1077]
Trying to use a package inside my evaluation code that uses a package that uses unsafe... _lmao_.

I'm able to make the first two packages available by cloning them to `go/src/github.com/gh-acc-name/gh-repo-name` but I can't get `unsafe` to be recognized. 

I've considered and tried ->
- `yaegi extract unsafe` which causes a file named `unsafe.go` to be generated in the current directory, doesn't fix my problem because I don't know what to do with the file and I still get the error when evaluating. 
- I don't know how to implement the `-unsafe` flag because I run my code through `go run main.go` and import the interpretation packages into my code and use them there.

The exact error I am getting is `import "unsafe" error: unable to find source related to: "unsafe"`.

I would appreciate any help on this...

**Comment by mvertes** [comment]
Yaegi already includes the support of unsafe, it is just not enabled by default (for security reasons). 

To enable it using the command line, use `-unsafe` flag (see command line doc https://pkg.go.dev/github.com/traefik/yaegi/cmd/yaegi).

To enable it if you embed the interpreter in another project:

```go
import  (
    "github.com/traefik/yaegi/interp"
    "github.com/traefik/yaegi/stdlib"
    "github.com/traefik/yaegi/stdlib/unsafe"
)

func main() {
   i := interp.New(interp.Options{})
   i.Use(stdlib.Symbols)
   i.Use(unsafe.Symbols)
   i.Eval( .... )
}
```

**Comment by ShadowNight573** [comment]
Once again, don't know how to implement the `-unsafe` flag. And the second option didn't seem to fix it either.

**Code:** https://github.com/ShadowNight573/Discord-Bot-Test/blob/main/bot/commands/debug/eval.go#L64

**Error:**
![image](https://user-images.githubusercontent.com/56423789/114786142-4622fd80-9d43-11eb-9aaf-0364eac8af5d.jpeg)

**Comment by ShadowNight573** [comment]
I'm unsure what this error means or how I can fix it... not sure if it's because of this package either. Got any ideas @mvertes?
![image](https://user-images.githubusercontent.com/56423789/114787348-415f4900-9d45-11eb-95f2-80dca26c4514.jpeg)

**Comment by mvertes** [comment]
Could you open a separate issue for the problem that you are facing now ? It may be a bug in yaegi.

The interesting part here is:
```go
import "github.com/gorilla/websocket"
```
and then the last part of the error message: `[...]/conn_write.go:13:12: undefined field or method: WriteTo`

Thanks
