### ISSUE TITLE
script import error using commit d16bd4bcdb86 onwards ( no error with previous commits )

### ISSUE THREAD

**Issue by TheMightyGit** [traefik/yaegi#1114]
I have no import errors (from my yaegi scripts) up to and including commit 33a532ee012c

But from d16bd4bcdb86 or later I get...

```
12:2: import "marv" error: unable to find source related to: "marv". Either the GOPATH environment variable, or the Interpreter.Options.GoPath needs to be set
```

I define the "marv" module as a programatic export (`export := map[string]map[string]reflect.Value{ "marv": map[string]reflect.Value{...} }` and have an `interpreter.Use(export)`, which has worked fine up until now.

**Comment by mvertes** [comment]
From this commit, the packages names are constructed with `importPath/packageName` (necessary to get the correct package name when it doesn't match the import path), so you have to specify:
```go
export := map[string]map[string]reflect.Value{
       "marv/marv": {       // instead of "marv":
            .....
        },
}

**Comment by TheMightyGit** [comment]
Perfect, that fixed it. Thank you <3
