### ISSUE TITLE
Make use of `fs.FS` (go 1.16 and up) so that source can be loaded from diverse filesystems.

### ISSUE THREAD

**Issue by TheMightyGit** [traefik/yaegi#1200]
### Proposal

I propose adding a `Filesystem fs.FS` field to `Config` so that the user can supply their own filesystem.

### Background

I use yeagi for my fantasy console, but I also target WASM where there is no default filesystem. Currently I use `Eval(string)` but it means I lose all the benfits of filesystem separation gained from `EvalPath()` resulting in huge monoliths of unseparated code.

As I already have and use an http zipfile `fs.FS` in my fantasy console, being able to set that FS for yaegi allows me to lay out files like a local filesystem (even tho it's dynamically loaded from a zipfile over http) and not have to use `Eval(string)` anymore.

### Workarounds

`Eval(string)`, but I lose all the benefits of file separation that `EvalPath()` gives.

I have started a PR #1199 to discuss how I see implementation (I was curious so I started impl before creating this feature request).

**Comment by mpl** [comment]
fyi, this https://github.com/traefik/yaegi/pull/1201 is now merged.

**Comment by TheMightyGit** [comment]
@mpl Hi. 1201 doesn't relate to this particular issue. This issue is for the feature of using fs.FS in the interpreter Config (see #1199 ) rather than being for the stdlib for fs.FS.
