### ISSUE TITLE
d16bd4bc breaks kortschak/yaegiconf

### ISSUE THREAD

**Issue by kortschak** [traefik/yaegi#1203]
### The following triggers an unexpected result

This bug is not a use of the interpreter as an executable, but as an embedded interpreter. So this field is not informative.

Attempt to run tests for github.com/kortschak/yaegiconf at or after d16bd4bcdb8685f7ce88a0ee2261f7d945a6cc84 fail. This can be seen here by running the tests on this branch https://github.com/kortschak/yaegiconf/tree/broken.

```go
package yaegiconf_test

import (
	"context"
	"fmt"
	"log"
	"reflect"

	"github.com/traefik/yaegi/interp"

	"github.com/kortschak/yaegiconf"
)

func Example_struct() {
	type Config struct {
		N int
		F float64
	}
	var c Config
	err := yaegiconf.EvalTo(&c, `config.Value{N: 5, F: 0.1}`)
	if err != nil {
		log.Fatalf("failed to parse configuration: %v", err)
	}

	fmt.Printf("%#v\n", c)

	// Output:
	//
	// yaegiconf_test.Config{N:5, F:0.1}
}
```

### Expected result

```console
$ go test            
PASS
ok  	github.com/kortschak/yaegiconf	10.004s
```

### Got

```console
$ go test                               
2021/07/26 10:11:44 failed to parse configuration: 1:21: import "config" error: unable to find source related to: "config". Either the GOPATH environment variable, or the Interpreter.Options.GoPath needs to be set
exit status 1
FAIL	github.com/kortschak/yaegiconf	0.002s
```

### Yaegi Version

d16bd4bcdb8685f7ce88a0ee2261f7d945a6cc84

### Additional Notes

It's pretty clear that I'm abusing package namespaces here, but it did previously work. I don't see any information in #1102 that shows how I should alter the use to make something like this work (and I suspect that the valid changes won't because this is running in a \_test package.

This is probably a documentation issue more than a correctness issue.

**Comment by TheMightyGit** [comment]
@kortschak  I think the map field here https://github.com/kortschak/yaegiconf/blob/broken/config.go#L39 needs to read `"config/config":` now.

**Comment by kortschak** [comment]
No, the key there is a lie, there is no source that the interpreter should be looking for on a file system. This appears to be due to a desire to perform type analysis, which isn't necessary in this case. Ideally, having an option to elide that would be provided.

**Comment by kortschak** [comment]
So using "config/config" allows me to get past the import path check, but it fails later.

It looks like the issue is that although the type should be treatable as belonging to a binary package (and is placed in the `binPkg` map) when the time comes to check this, it fails the test [here](https://github.com/traefik/yaegi/blob/c80c605ab99e779cc9e6e37f00d0ddbdbc107c5e/interp/gta.go#L190); the map is keyed on the package name, but the query is performed with the import path. This can be seen by adding this 
```diff
diff --git a/interp/gta.go b/interp/gta.go
index 7497e7f..c00ebb1 100644
--- a/interp/gta.go
+++ b/interp/gta.go
@@ -1,6 +1,7 @@
 package interp
 
 import (
+       "fmt"
        "path/filepath"
        "reflect"
 )
@@ -187,6 +188,10 @@ func (interp *Interpreter) gta(root *node, rpath, importPath string) ([]*node, e
                        }
                        // Try to import a binary package first, or a source package
                        var pkgName string
+                       fmt.Printf("ipath=%q binPkg=%#v\n", ipath, interp.binPkg)
                        if pkg := interp.binPkg[ipath]; pkg != nil {
                                switch name {
                                case "_": // no import of symbols
```
Which outputs:
```
ipath="config/config" binPkg=interp.Exports{"":map[string]reflect.Value{"_error":reflect.Value{typ:(*reflect.rtype)(0x690b20), ptr:(unsafe.Pointer)(nil), flag:0x16}}, "config":map[string]reflect.Value{"Value":reflect.Value{typ:(*reflect.rtype)(0x67ef60), ptr:(unsafe.Pointer)(nil), flag:0x16}}}
```
I can paper over this by coniditionally converting "config/config" to "config", but clearly this is not a fix.

Given that there is an explicit check for directory components of imports paths, the test here needs to be aware of that. Making this change does that, but is horrible.
```diff
diff --git a/interp/gta.go b/interp/gta.go
index 7497e7f..917d865 100644
--- a/interp/gta.go
+++ b/interp/gta.go
@@ -1,6 +1,7 @@
 package interp
 
 import (
+       "path"
        "path/filepath"
        "reflect"
 )
@@ -187,6 +188,11 @@ func (interp *Interpreter) gta(root *node, rpath, importPath string) ([]*node, e
                        }
                        // Try to import a binary package first, or a source package
                        var pkgName string
+                       if packageName := path.Base(ipath); path.Dir(ipath) == packageName {
+                               ipath = packageName
+                       }
                        if pkg := interp.binPkg[ipath]; pkg != nil {
                                switch name {
                                case "_": // no import of symbols
```

**Comment by kortschak** [comment]
@mvertes Would the diff above be an acceptable fix for you?

**Comment by mvertes** [comment]
@kortschak Yes it would.
