### ISSUE TITLE
go playground example broken

### ISSUE THREAD

**Issue by jmccormick2001** [traefik/yaegi#1212]
### The following program `sample.go` triggers an unexpected result

```go
the go playground example on the main github page is broken
```

### Expected result

```console
the example appears to be broken in go playground
```

### Got

```console
the code appears to not build in go playground
```

### Yaegi Version

latest version

**Comment by ldez** [comment]
Hello,
I think it's related to the current GitHub incident https://www.githubstatus.com/

**Comment by jmccormick2001** [comment]
timeout running go build
go: finding module for package github.com/traefik/yaegi/stdlib
go: finding module for package github.com/traefik/yaegi/interp
go: downloading github.com/traefik/yaegi v0.9.21
go: found github.com/traefik/yaegi/interp in github.com/traefik/yaegi v0.9.21
go: found github.com/traefik/yaegi/stdlib in github.com/traefik/yaegi v0.9.21

**Comment by jmccormick2001** [comment]
I see that when I try to run it.  I'll try it later today to retest.

**Comment by jmccormick2001** [comment]
fixed now it appears.
