### ISSUE TITLE
interp: add a function to compile AST (instead of source)

### ISSUE THREAD

**Issue by firelizzard18** [traefik/yaegi#1251]
### Proposal

```go
func (interp *Interpreter) CompileAST(ast.Node) (*Program, error)
```

This would accept Go AST provided by the user. Currently, the two supported pathways, compile a file and compile a function body, are equivalent to passing in an `*ast.File` or an `*ast.BlockStmt`, respectively. The new function could explicitly support only a File or BlockStmt input, though the existing `(*Interpreter).ast` may handle arbitrary (valid) ASTs.

I wrote a relatively small [patch](https://github.com/traefik/yaegi/compare/master...firelizzard18:compile-ast) for this. Would you accept this as a PR?

### Background

I'm playing around with writing a Go-/Yaegi-based shell. I want to support string interpolation and other features foreign to Go. This would require manipulation of the AST. While I could generate source, I would much prefer to directly pass the modified AST to Yaegi.

### Workarounds

Parsing the source, modifying the AST, writing it back out to a buffer, and handing that buffer to Yaegi, which would parse the source again.

**Comment by mvertes** [comment]
Thanks for this proposal. It is ok to me, as the standard lib AST format is stable and already in use by many tools / libraries in the Go ecosystem. The patch looks good too.
