### ISSUE TITLE
Interpreting all Go files within a directory

### ISSUE THREAD

**Issue by karelorigin** [traefik/yaegi#1314]
### Proposal

The current Yaegi release does not support loading multiple Go files from a directory. This is something that is possible in native Go and is usually seen in non-main packages:

```golang
// foo.go
package example

func foo() {
       bar() // calling function located in other file
}
```

```golang
// bar.go
package example

import (
     "fmt"
)

func bar() {
    fmt.Println("hello there")
}
```

I propose adding a new method to`*interp.Interpeter*` that can satisfy this need. The end result would look something like this:

```shell
user:app user$ ls
bar.go	foo.go
```

```golang
_, err = i.EvalDir("/tmp/app")
if err != nil {
   return err
}
```

### Background

Splitting large files into multiple, smaller files for better readability and maintainability.

### Workarounds

In the past, I've managed to work my way around this issue by using `go/ast` to merge the files into one. This isn't very convenient and not ideal as you might run into a bunch of issues (duplicate package imports, etc)

**Comment by mvertes** [comment]
Loading multiple files from a directory already works in yaegi. All you have to do is have the package directory in the GOPATH (which also can be set a interpreter creation) and invoke `interp.EvalPath` on it.
For example, if GOPATH is set to `~/go`, and your example is in `~/go/src/example`, then
`interp.EvalPath("example")` will function, or from inside a yaegi script: `import "example"`.

**Comment by karelorigin** [comment]
Hey @mvertes. This is indeed true for importing packages but what I meant was directly eval'ing the directory (a non-main package) and treating them as standalone programs.
