### ISSUE TITLE
Import "github.com/go-sql-driver/mysql" by go:generate yaegi extract failed

### ISSUE THREAD

**Issue by hemmmapart** [traefik/yaegi#1352]
### The following program `sample.go` triggers an unexpected result

```go
package main

import (
	"fmt"
	"os"
	"reflect"
	"time"

	"yaegiBenchmark/dbtest"

	_ "github.com/go-sql-driver/mysql"
	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
)

func main() {
	startTime := time.Now()
	test(40)
	timeUsed := time.Now().Sub(startTime).Microseconds()
	fmt.Println("TimeUsed:", timeUsed)
}

func test(testNum int) {
	var goPath string = "/Users/licha/Downloads/gopath"
	intp := interp.New(interp.Options{GoPath: goPath,
		Env: os.Environ()})
	intp.Use(stdlib.Symbols)
	intp.Use(dbtest.Symbols)

	fmt.Println("Before Eval")
	intp.Eval("./dbtest/dbtest.go")
	intp.Eval("./dbtest/github_com-go-sql-driver-mysql.go")
	var err error
	// if _, err := intp.Eval(`import "dbtest"`); err != nil {
	// 	panic(err)
	// }
	fmt.Println("Before QueryDb")
	v, _ := intp.Eval("dbtest.QueryDb")
	fmt.Println(reflect.TypeOf(dbtest.QueryDb))
	fu := v.Interface().(func(int) int)
	fmt.Printf("Fib(%d) =%d\n", testNum, fu(testNum))
	if err != nil {
		panic(err)
	}

}

--------------------------------------------------------------------
// Code generated by 'yaegi extract github.com/go-sql-driver/mysql'. DO NOT EDIT.

package dbtest

import (
	"github.com/go-sql-driver/mysql"
	"reflect"
)

func init() {
	Symbols["github.com/go-sql-driver/mysql/mysql"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DeregisterLocalFile":     reflect.ValueOf(mysql.DeregisterLocalFile),
		"DeregisterReaderHandler": reflect.ValueOf(mysql.DeregisterReaderHandler),
		"DeregisterServerPubKey":  reflect.ValueOf(mysql.DeregisterServerPubKey),
		"DeregisterTLSConfig":     reflect.ValueOf(mysql.DeregisterTLSConfig),
		"ErrBusyBuffer":           reflect.ValueOf(&mysql.ErrBusyBuffer).Elem(),
		"ErrCleartextPassword":    reflect.ValueOf(&mysql.ErrCleartextPassword).Elem(),
		"ErrInvalidConn":          reflect.ValueOf(&mysql.ErrInvalidConn).Elem(),
		"ErrMalformPkt":           reflect.ValueOf(&mysql.ErrMalformPkt).Elem(),
		"ErrNativePassword":       reflect.ValueOf(&mysql.ErrNativePassword).Elem(),
		"ErrNoTLS":                reflect.ValueOf(&mysql.ErrNoTLS).Elem(),
		"ErrOldPassword":          reflect.ValueOf(&mysql.ErrOldPassword).Elem(),
		"ErrOldProtocol":          reflect.ValueOf(&mysql.ErrOldProtocol).Elem(),
		"ErrPktSync":              reflect.ValueOf(&mysql.ErrPktSync).Elem(),
		"ErrPktSyncMul":           reflect.ValueOf(&mysql.ErrPktSyncMul).Elem(),
		"ErrPktTooLarge":          reflect.ValueOf(&mysql.ErrPktTooLarge).Elem(),
		"ErrUnknownPlugin":        reflect.ValueOf(&mysql.ErrUnknownPlugin).Elem(),
		"NewConfig":               reflect.ValueOf(mysql.NewConfig),
		"NewConnector":            reflect.ValueOf(mysql.NewConnector),
		"ParseDSN":                reflect.ValueOf(mysql.ParseDSN),
		"RegisterDial":            reflect.ValueOf(mysql.RegisterDial),
		"RegisterDialContext":     reflect.ValueOf(mysql.RegisterDialContext),
		"RegisterLocalFile":       reflect.ValueOf(mysql.RegisterLocalFile),
		"RegisterReaderHandler":   reflect.ValueOf(mysql.RegisterReaderHandler),
		"RegisterServerPubKey":    reflect.ValueOf(mysql.RegisterServerPubKey),
		"RegisterTLSConfig":       reflect.ValueOf(mysql.RegisterTLSConfig),
		"SetLogger":               reflect.ValueOf(mysql.SetLogger),

		// type definitions
		"Config":          reflect.ValueOf((*mysql.Config)(nil)),
		"DialContextFunc": reflect.ValueOf((*mysql.DialContextFunc)(nil)),
		"DialFunc":        reflect.ValueOf((*mysql.DialFunc)(nil)),
		"Logger":          reflect.ValueOf((*mysql.Logger)(nil)),
		"MySQLDriver":     reflect.ValueOf((*mysql.MySQLDriver)(nil)),
		"MySQLError":      reflect.ValueOf((*mysql.MySQLError)(nil)),
		"NullTime":        reflect.ValueOf((*mysql.NullTime)(nil)),

		// interface wrapper definitions
		"_Logger": reflect.ValueOf((*_github_com_go_sql_driver_mysql_Logger)(nil)),
	}
}

// _github_com_go_sql_driver_mysql_Logger is an interface wrapper for Logger type
type _github_com_go_sql_driver_mysql_Logger struct {
	IValue interface{}
	WPrint func(v ...interface{})
}

func (W _github_com_go_sql_driver_mysql_Logger) Print(v ...interface{}) {
	W.WPrint(v...)
}
```

### Expected result

```console
go run main.go
// output
Before Eval
Before QueryDb
func()
Fib(40)=102334155
```

### Got

```console
go run main.go
// output
Before Eval
Before QueryDb
func()
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x1, 0x7)
        /usr/local/go1.16.7/src/reflect/value.go:1021 +0x174
reflect.Value.Interface(...)
        /usr/local/go1.16.7/src/reflect/value.go:1016
main.test(0x28)
        /Users/licha/Downloads/gopath/src/yaegiBenchmark/main.go:40 +0x2a0
main.main()
        /Users/licha/Downloads/gopath/src/yaegiBenchmark/main.go:18 +0x44
exit status 2
```

### Yaegi Version

0.11.2

### Additional Notes

I'm trying to use yaegi to load some third party package at golang runtime, and I use
`//go:generate go install github.com/go-sql-driver/mysql
//go:generate yaegi extract github.com/go-sql-driver/mysql`
in package dbtest, it generated a file named github_com-go-sql-driver-mysql.go, then I use
`intp.Use(dbtest.Symbols)`in my code, trying to inject the `mysql` Symbols to my  interpreter, but I got the error "reflect: call of reflect.Value.Interface on zero Value"

Is there a doc that i can refer to? `stdlib.Symbols` really confused me, could you please show me a right way to do it, thanks a lot~

**Comment by hemmmapart** [comment]
My dir tree is:
yaegiBenchmark
    -dbtest
        --dbtest.go
        --github_com-go-sql-driver-mysql.go
    -vendor
        --github.com
            --go-sql-driver
            --traefik
    -go.sum
    -go.mod
    -main.go

and the dbtest.go:
`//go:generate go install github.com/go-sql-driver/mysql
//go:generate yaegi extract github.com/go-sql-driver/mysql

package dbtest

import (
	"database/sql"
	"fmt"
	"reflect"

	// _ "github.com/go-sql-driver/mysql"
	_ "github.com/traefik/yaegi/interp"
	_ "github.com/traefik/yaegi/stdlib"
)

// type dbInfo struct {
// 	config
// }

var (
	db      *sql.DB
	Symbols = map[string]map[string]reflect.Value{}
)

func QueryDb() {
	dsn := "mkkk:mkkk99@tcp(127.0.0.1:3306)/mkkkTest"
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		fmt.Println("connect to database failed:", err)
		return
	}
	rows, err := db.Query("select * from `gate_benchmark`")
	defer rows.Close()
	if err != nil {
		fmt.Println("err:", err)
		return
	}

	for rows.Next() {
		var slot_num int
		var ectd_addr string
		var fid string
		rows.Scan(&slot_num, &ectd_addr, &fid)
		fmt.Println(slot_num, ectd_addr, fid)
	}

	err = rows.Err()
	if err != nil {
		fmt.Println("other error:", err)
		return
	}

}
`

**Comment by hemmmapart** [comment]
My dir tree is:
yaegiBenchmark
-dbtest
--dbtest.go
--github_com-go-sql-driver-mysql.go
-vendor
--github.com
--go-sql-driver
--traefik
-go.sum
-go.mod
-main.go

and the dbtest.go:
`
//go:generate go install github.com/go-sql-driver/mysql
//go:generate yaegi extract github.com/go-sql-driver/mysql

package dbtest

import (
"database/sql"
"fmt"
"reflect"

// _ "github.com/go-sql-driver/mysql"
_ "github.com/traefik/yaegi/interp"
_ "github.com/traefik/yaegi/stdlib"
)

// type dbInfo struct {
// config
// }

var (
db *sql.DB
Symbols = map[string]map[string]reflect.Value{}
)

func QueryDb() {
dsn := "mkkk:mkkk99@tcp(127.0.0.1:3306)/mkkkTest"
db, err := sql.Open("mysql", dsn)
if err != nil {
fmt.Println("connect to database failed:", err)
return
}
rows, err := db.Query("select * from gate_benchmark")
defer rows.Close()
if err != nil {
fmt.Println("err:", err)
return
}

for rows.Next() {
	var slot_num int
	var ectd_addr string
	var fid string
	rows.Scan(&slot_num, &ectd_addr, &fid)
	fmt.Println(slot_num, ectd_addr, fid)
}

err = rows.Err()
if err != nil {
	fmt.Println("other error:", err)
	return
}
}
`

**Comment by hemmmapart** [comment]
My dir tree is:
yaegiBenchmark
-dbtest
    --dbtest.go
    --github_com-go-sql-driver-mysql.go
-vendor
    --github.com
        ---go-sql-driver
        ---traefik
-go.sum
-go.mod
-main.go

and the dbtest.go:

`//go:generate go install github.com/go-sql-driver/mysql
//go:generate yaegi extract github.com/go-sql-driver/mysql

package dbtest

import (
"database/sql"
"fmt"
"reflect"

// _ "github.com/go-sql-driver/mysql"
_ "github.com/traefik/yaegi/interp"
_ "github.com/traefik/yaegi/stdlib"
)

// type dbInfo struct {
// config
// }

var (
db *sql.DB
Symbols = map[string]map[string]reflect.Value{}
)

func QueryDb() {
dsn := "mkkk:mkkk99@tcp(127.0.0.1:3306)/mkkkTest"
db, err := sql.Open("mysql", dsn)
if err != nil {
fmt.Println("connect to database failed:", err)
return
}
rows, err := db.Query("select * from gate_benchmark")
defer rows.Close()
if err != nil {
fmt.Println("err:", err)
return
}

for rows.Next() {
	var slot_num int
	var ectd_addr string
	var fid string
	rows.Scan(&slot_num, &ectd_addr, &fid)
	fmt.Println(slot_num, ectd_addr, fid)
}

err = rows.Err()
if err != nil {
	fmt.Println("other error:", err)
	return
}
}
`

**Comment by bailsman** [comment]
I tried to reproduce your example and I'm not completely clear what you intend to run as interpreted code and what as binary.

If dbtest.go should be compiled and used as binary symbols, you need to make your own symbols array following yaegi extract's example. Like this:

```go
import "yaegiBenchmark/dbtest"
dbtestSymbols["dbtest/dbtest"] = map[string]reflect.Value{
                "QueryDb": reflect.ValueOf(dbtest.QueryDb),
}
intp.use(dbtestSymbols)
```

Then any source you evaluate inside the interpreter can do "import dbtest" and call "dbtest.QueryDB()":

```go
v, err = intp.Eval("dbtest.QueryDB()")
```

In this case you don't need to yaegi extract the sql driver at all - it will be compiled into dbtest already by the go compiler when compiling your main.go.

Do you instead intend dbtest.go to be interpreted (and only the mysql driver to be compiled as binary)? In that case maybe I would separate the mysql driver package (to be compiled as binary and used as symbols) and dbtest (to be interpreted).

**Comment by hemmmapart** [comment]
Thanks for reply, I want to load & compile dbtest.go at go Runtime, read it to the program's memory and use its function such as dbtest.QueryDb. Thus I can change the content of dbtest.go dynamically. I run this well if there is not use of Third-party packages in dbtest.go.

But when dbtest.QueryDb relay on Third-party packages like 'go-sql-driver', The program went wrong.

So I wonder whether I could load the Symbols of 'go-sql-driver' in my main.go and inject it into my interpreter to let my interpreter use  'go-sql-driver' well.

Am I using it in a wrong way?

**Comment by bailsman** [comment]
I think it is working for me with these changes:

Directory structure:

```
yaegiBenchmark/
    dbtest/
        dbtest.go
    go.mod
    go.sum
    main.go
    mysqldriver/
        github_com-go-sql-driver-mysql.go
```

```go
// dbtest.go

package dbtest

import (
        "database/sql"
        "fmt"
        _ "github.com/go-sql-driver/mysql"
)

var (
        db *sql.DB
)

func QueryDb() {
        dsn := "mkkk:mkkk99@tcp(127.0.0.1:3306)/mkkkTest"
        db, err := sql.Open("mysql", dsn)
        if err != nil {
                fmt.Println("connect to database failed:", err)
                return
        }
        rows, err := db.Query("select * from gate_benchmark")
        defer rows.Close()
        if err != nil {
                fmt.Println("err:", err)
                return
        }

        for rows.Next() {
                var slot_num int
                var ectd_addr string
                var fid string
                rows.Scan(&slot_num, &ectd_addr, &fid)
                fmt.Println(slot_num, ectd_addr, fid)
        }

        err = rows.Err()
        if err != nil {
                fmt.Println("other error:", err)
                return
        }
}
```

```go
// main.go

package main

import (
        "fmt"
        "os"
        "reflect"
        "time"

        "yaegiBenchmark/mysqldriver"

        "github.com/traefik/yaegi/interp"
        "github.com/traefik/yaegi/stdlib"
)

func main() {
        startTime := time.Now()
        test(40)
        timeUsed := time.Now().Sub(startTime).Microseconds()
        fmt.Println("TimeUsed:", timeUsed)
}

func test(testNum int) {
        var goPath string = "/Users/licha/Downloads/gopath"
        intp := interp.New(interp.Options{GoPath: goPath,
                Env: os.Environ()})
        intp.Use(stdlib.Symbols)
        intp.Use(mysqldriver.Symbols)

        fmt.Println("Before EvalPath")
        _, err := intp.EvalPath("./dbtest/dbtest.go")
        if err != nil {
                panic(err)
        }

        fmt.Println("Before QueryDb")
        v, _ := intp.Eval("dbtest.QueryDb")
        if err != nil {
                panic(err)
        }

        fmt.Println(reflect.TypeOf(v))
        fu := v.Interface().(func())
        fu()
}
```

Output of `go run .`

```
Before EvalPath
Before QueryDb
reflect.Value
0 foo bar
1 foo1 bar1
TimeUsed: 5171
```

I have also added the line `var Symbols = map[string]map[string]reflect.Value{}` to github_com-go-sql-driver-mysql.go and changed the package line at the top to `package mysqldriver`

**Comment by hemmmapart** [comment]
Thank you so much! It also works for me, thanks for reply again~
