### ISSUE TITLE
Support Go 1.18

### ISSUE THREAD

**Issue by olavfosse** [traefik/yaegi#1363]
### Proposal

There's not much to add to the title... This project looks really cool and I'd like to use it with the latest Go 1.18.

### Background

foo

### Workarounds

bar

**Comment by mvertes** [comment]
Hello, for your information, the support of Go generics in yaegi is not ready yet. When ready, it should be made available in the main branch after the release of go1.19, for compatibility reasons, as we support the 2 last Go versions and go1.17.x is incompatible with generics.
