### ISSUE TITLE
Issue with non-exported method interface definition with binary mode

### ISSUE THREAD

**Issue by cclerget** [traefik/yaegi#1373]
### The following program `sample.go` triggers an unexpected result

```go
package main

import (
	"fmt"
	"go/ast"
)

func NewBadExpr() ast.Expr {
	return &ast.BadExpr{}
}

func main() {
	fmt.Printf("%T\n", NewBadExpr().(*ast.BadExpr))
}
```

### Expected result

```console
$ go run ./sample.go
*ast.BadExpr
```

### Got

```console
$ yaegi ./sample.go
impossible type assertion: *ast.BadExpr does not implement ast.Expr (missing exprNode method)
```

### Yaegi Version

v0.11.2

**Comment by mvertes** [comment]
I tried to reproduce this issue on v0.11.2 and on HEAD of master, and could not, obtaining always the expected result. Are you sure of this ?

**Comment by cclerget** [comment]
Yes, I just updated the reproducer based on #1374

**Comment by cclerget** [comment]
Yes, I just updated the reproducer based on #1374
