### ISSUE TITLE
import \"slices\" error: unable to find source related to: \"slices\"

### ISSUE THREAD

**Issue by darkweak** [traefik/yaegi#1608]
### The following program `sample.go` triggers an unexpected result

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	vals := []string{"A", "B", "C"}
	if slices.Contains(vals, "*") {
		fmt.Println("found")
		return
	}

	fmt.Println("not found")
}
```

### Expected result

```console
found
```

### Got

```console
import \"slices\" error: unable to find source related to: \"slices\"
```

### Yaegi Version

v0.15.1

### Additional Notes

That affects the latest Traefik version!

**Comment by ldez** [comment]
Hello,

Yaegi supports go1.19 and go1.20.
https://github.com/traefik/yaegi?tab=readme-ov-file#features

go1.21 and higher are not supported https://github.com/traefik/yaegi/pull/1598
