### ISSUE TITLE
panic: reflect.Value.Call: call of nil function

### ISSUE THREAD

**Issue by duj4** [traefik/yaegi#1663]
### The following program `sample.go` triggers an unexpected result

package main

func main() {
  cmap.Upsert()
}

### Expected result

There should be no error coming out.

### Got

Error like "panic: reflect.Value.Call: call of nil function" posted, which caused the pod reboot.

### Yaegi Version

0.16.1

### Additional Notes

I am writing a Traefik plugin with https://github.com/orcaman/concurrent-map/tree/v1.0.0 imported. However, error like below posted while it is running for while:

![Image](https://github.com/user-attachments/assets/76aac713-d02c-4a68-bfbe-bd72eaa2315c)

Code snippet is as below:
![Image](https://github.com/user-attachments/assets/c5c72f45-2648-4c62-b92b-b23ddb5eb85c)

**Comment by Autumn-27** [comment]
May I ask if there is a solution?

**Comment by duj4** [comment]
@Autumn-27 sorry I did not dig further as I switched to another way for storing the data.
