### ISSUE TITLE
Impossible local import

### ISSUE THREAD

**Issue by morzan1001** [traefik/yaegi#1666]
Hi, I would like to write a plugin for traefik. I don't have much experience with yaegi but I have written code and tests in go that look bug free to me now and run with go test for example.

My plugin needs protofiles. Therefore I have a folder with the name “proto” and I import them. No problem with go. Yaegi, on the other hand, says: 
```
error: unable to find source related to: “github.com/morzan1001/forward_auth_grpc_plugin/proto”
```
I did a little research and saw that you have to use external resources in yaegi somehow with `yaegi extract` and then the passed wrapper. But now it's not an external package at all, everything is simply in the “proto” folder. 

I would be grateful for help.

PS: I have shortened the code in the code examples. The full gofile would otherwise be found here: [https://github.com/morzan1001/forward_auth_grpc_plugin](https://github.com/morzan1001/forward_auth_grpc_plugin)

### The following program `import` triggers an unexpected result

```go
package main

import (
<...>

	pb "github.com/morzan1001/forward_auth_grpc_plugin/proto"

<...>
)
<...>
```

### Expected result

```
$ go test
PASS
ok      github.com/morzan1001/forward_auth_grpc_plugin  10.054s
```

### Got

```
$ yaegi test
test: forward_auth_grpc.go:10:2: import "github.com/morzan1001/forward_auth_grpc_plugin/proto" error: unable to find source related to: "github.com/morzan1001/forward_auth_grpc_plugin/proto"
````

### Yaegi Version

`devel / v0.16.1`

**Comment by SolarLune** [comment]
Hello - you closed this issue, but I'm intrigued to see what you did. It sounds like you were importing a subdirectory as a package, and that's where the issue came in. I am doing something similar - where did you run into the issue?
