### ISSUE TITLE
undefined package in some cases

### ISSUE THREAD

**Issue by tim-st** [traefik/yaegi#289]
Tested in REPL latest version with `go version go1.12.7 windows/amd64` and `go version go1.12.7 linux/amd64`.
```
> import "github.com/tim-st/go-zim"
C:\Users\-\go\src\github.com\tim-st\go-zim\checksum.go:11:37: undefined: md5
>
```
The target file is [here](https://github.com/tim-st/go-zim/blob/cf9654857e4c7ca705e957570eba740ce009682c/checksum.go#L11).
When manually `import "crypto/md5"` before, this specific error doesn't appear.

**Comment by mvertes** [comment]
Probably related to #152

**Comment by tim-st** [comment]
On WSL-Ubuntu (`go version go1.12.7 linux/amd64`) I get the same results.

**Comment by ldez** [comment]
There are 2 different problems in this issue:
- `undefined: md5` is related to `[md5.Size]byte`: the size of the output array is a constant from another package.
- `undefined: unicat` is related to the import syntax: `unicat` is used as an "alias" to `go-unicat`.

**Comment by tim-st** [comment]
@ldez I've put the second part [here](https://github.com/containous/yaegi/issues/298).

`unicat` wasn't alias for `go-unicat`, it was an alias for `unicat` (the identity).

**Comment by tim-st** [comment]
With the latest version the following appears now:

```
> import "github.com/tim-st/go-zim"
C:\Users\-\go\src\github.com\xi2\xz\dec_stream.go:42:23: CFG post-order panic: reflect: call of reflect.Value.Int on uint64 Value
```

**Comment by mpl** [comment]
I think this issue might be fixed now:

``` go
% yaegi
> import zim "github.com/tim-st/go-zim"
: 0xc000184420
> println(zim.MagicNumber)
72173914
> 
```

@tim-st Could you please confirm?

**Comment by tim-st** [comment]
@mpl Your code produces a new error for me:
```
> import zim "github.com/tim-st/go-zim"
1:21: import "github.com/tim-st/go-zim" error: C:\Users\-\go\src\github.com\tim-st\go-zim\file.go:8:2: import "github.com/xi2/xz" error: C:\Users\-\go\src\github.com\xi2\xz\reader.go:80:10: cannot use type *github.com/xi2/xz.xzDec as type *github.com\xi2\xz.xzDec in assignment
```

But I can create separate issue for this.
