### ISSUE TITLE
generate: speed-up symbols generation via goexports

### ISSUE THREAD

**Issue by sbinet** [traefik/yaegi#314]
on my machine (8procs, 64G RAM, SSDs), running `go generate` or `make generate` takes quite some time.
it seems the bulk of the time is taken by generating the symbols for the whole `stdlib`:

```
$> time go generate ./stdlib

real	0m24.299s
user	0m59.147s
sys	0m4.024s
```

one could probably refactor a bit the symbols generation by giving the whole list of stdlib packages to wrap to `goexports` and, within `goexports`, launch a bunch of goroutines to process each package.

applying that suggestion, I came up with:

```
$> time go generate ./stdlib

real	0m9.747s
user	1m3.719s
sys	0m4.642s
```

interested in a PR?

**Comment by mvertes** [comment]
As `goexports`, now `internal/cmd/extract` is performed only once by the maintainer for generating wrappers, it is not considered as performance critical, and we do not have interest to speed it up.
Thanks.
