### ISSUE TITLE
license apache2 or MIT

### ISSUE THREAD

**Issue by glycerine** [traefik/yaegi#321]
Some folks will find the Apache2 license a hinderance. It would be great to have a Go interpreter that can be used absolutely anywhere.  Would you consider offering Yaegi under the user's choice of license, Apache2 or MIT?  Or just MIT.

**Comment by mvertes** [comment]
Traefik Labs (previously Containous) has no plan to change the Apache 2 license of yaegi. We haven't got other requests since this issue was opened (more than 14 months now), so I'm closing it.
