### ISSUE TITLE
borrow from gi -- esp for typechecking

### ISSUE THREAD

**Issue by glycerine** [traefik/yaegi#322]
I would invite you to borrow code liberally from my Go interpreter, gi, which is MIT licensed.

https://github.com/gijit/gi

I re-used the actual Go front end for parsing and type checking.  I saw a mention on a github issue that you weren't doing typechecking on code text yet... not sure if this is true, but if so, the actual Go typechecker is pretty easy to use. See `gi` for how it is done.  Any questions, let me know.

**Comment by glycerine** [comment]
would probably solve these very quickly:
https://github.com/containous/yaegi/issues/315
https://github.com/containous/yaegi/issues/308
https://github.com/containous/yaegi/issues/292
https://github.com/containous/yaegi/issues/286
https://github.com/containous/yaegi/issues/278
https://github.com/containous/yaegi/issues/274
https://github.com/containous/yaegi/issues/230

**Comment by mvertes** [comment]
Type checking is now mostly done (yaegi-0.9.3). Issues referenced above are now closed, except #315 which is a proposal, so I"m closing this one as well.
