### ISSUE TITLE
goexports: failed to format source for local package

### ISSUE THREAD

**Issue by tristan-cartledge-sd** [traefik/yaegi#419]
The following program `library.go` triggers a `failed to format source` error:

```go
package library

// Test is ...
func Test() {

}
```

Expected result:
```console
$ goexports <REDACTEDPATH>toolbelt/library
// output success?
```

Got:
```console
$ goexports <REDACTEDPATH>/library
2019/10/18 09:57:18 failed to format source: 7:10: expected ';', found ':' (and 2 more errors): // Code generated by 'goexports <REDACTEDPATH>toolbelt/library'. DO NOT EDIT.



// +build go1.13,!go1.14

package C:\dev\toolbelt

import (
        "<REDACTEDPATH>/library"
        "reflect"
)

func init() {
        Symbols["<REDACTEDPATH>/toolbelt/library"] = map[string]reflect.Value{
                // function, constant and variable definitions
                "Test": reflect.ValueOf(library.Test),

        }
}
```

I am basically trying to import a package of simple functions to our go scripts, and my understanding this is done via the Interpreter.Use method and I need to export symbols to do so?

**Comment by mpl** [comment]
Ignoring the fact that you're on windows and that may cause additional problems, that should now work with the new `yaegi extract` command.
Can you please confirm that we can now close this issue?

**Comment by mvertes** [comment]
Closing this issue due to age and no response. A new one can be opened if necessary.
