### ISSUE TITLE
Interface defined in interpreter not picked up by fmt.Println

### ISSUE THREAD

**Issue by cosmos72** [traefik/yaegi#435]
The following program `sample.go` has wrong output:

```go
package main

import (
	"fmt"
)

type Foo int

func (Foo) String() string {
	return "foo"
}

func print(arg interface{}) {
	fmt.Println(arg)
}

func main() {
	var arg Foo
	var f = print
	f(arg)
}
```

Expected result:
```console
$ go run ./sample.go
foo
```

Got:
```console
$ yaegi ./sample.go
0
```

It appears that `fmt.Println` does not see that `Foo` declared in the interpreter implements `fmt.Stringer` and simply outputs the int value.

I met the same problem with my interpreter gomacro and I have no idea how to fix this - except by "cheating" (i.e. replacing `fmt.Println` with an interpreter-aware implementation)

**Comment by mvertes** [comment]
reopening as #722 is reverted.
