### ISSUE TITLE
Question - How can I pass a struct to a scripted function

### ISSUE THREAD

**Issue by p4tin** [traefik/yaegi#478]
I wrote this toy example to illustrate my question - when I run this I get an error from Yaegi (`incomplete type`)...  How do I fix this?
```
package main

import "github.com/containous/yaegi/interp"

const src = `package foo
func Bar(d *main.Data) string { return d.Message + "-Foo" }`

type Data struct {
	Message string
}

func main() {
	d := Data{
		Message: "Kung",
	}
	
	i := interp.New(interp.Options{})

	_, err := i.Eval(src)
	if err != nil {
		panic(err)
	}

	v, err := i.Eval("foo.Bar")
	if err != nil {
		panic(err)
	}

	bar := v.Interface().(func(*Data) string)

	r := bar(&d)
	println(r)
}
```

I get the followinf stack trace on the go playground:
```
panic: 2:12: incomplete type 

goroutine 1 [running]:
github.com/containous/yaegi/interp.(*itype).frameType(0x849ab0, 0x499264, 0x0, 0x0)
	/tmp/gopath259824945/pkg/mod/github.com/containous/yaegi@v0.7.2/interp/type.go:948 +0x260
github.com/containous/yaegi/interp.(*scope).add(0x83e9a0, 0x849ab0, 0x85a630, 0x0)
	/tmp/gopath259824945/pkg/mod/github.com/containous/yaegi@v0.7.2/interp/scope.go:151 +0x40
github.com/containous/yaegi/interp.(*Interpreter).cfg.func1(0x85a240, 0x3, 0x849501, 0x6b01)
	/tmp/gopath259824945/pkg/mod/github.com/containous/yaegi@v0.7.2/interp/cfg.go:295 +0x3580
github.com/containous/yaegi/interp.(*node).Walk(0x85a240, 0x82be88, 0x82bea4, 0x0)
	/tmp/gopath259824945/pkg/mod/github.com/containous/yaegi@v0.7.2/interp/interp.go:164 +0x120
github.com/containous/yaegi/interp.(*node).Walk(0x85a120, 0x82be88, 0x82bea4, 0x80e0d7)
	/tmp/gopath259824945/pkg/mod/github.com/containous/yaegi@v0.7.2/interp/interp.go:168 +0x80
github.com/containous/yaegi/interp.(*Interpreter).cfg(0x872180, 0x85a120, 0x80e0d7, 0x3, 0x0, 0x0, 0x0, 0x0)
	/tmp/gopath259824945/pkg/mod/github.com/containous/yaegi@v0.7.2/interp/cfg.go:48 +0x180
github.com/containous/yaegi/interp.(*Interpreter).Eval(0x872180, 0x2ee867, 0x47, 0x0, 0x0, 0x6bb6, 0x872180, 0x16, 0x0, 0x6bb6)
	/tmp/gopath259824945/pkg/mod/github.com/containous/yaegi@v0.7.2/interp/interp.go:322 +0x1e0
main.main()
	/tmp/sandbox574545050/prog.go:19 +0xe0
```

Go Playground link: https://play.golang.org/p/udc3O_4fT5C

**Comment by ashneverdawn** [comment]
Don't know if there's a way to do it without reflection, but here's what I did:

`package main

//Note the additional imports
import (
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
	"reflect"
)

//Note 'custom' lib was imported
const src = `package foo
import "custom"
func Bar(d *custom.Data) string { return d.Message + "-Foo" }`

type Data struct {
	Message string
}

func main() {
	d := Data{
		Message: "Kung",
	}
	
	i := interp.New(interp.Options{})
	
	//This allows use of standard libs
	i.Use(stdlib.Symbols)
	
	//This will make a 'custom' lib  available that can be imported and contains your Data struct
	custom := make(map[string]map[string]reflect.Value)
	custom["custom"] = make(map[string]reflect.Value)
	custom["custom"]["Data"] = reflect.ValueOf((*Data)(nil))
	i.Use(custom)

	_, err := i.Eval(src)
	if err != nil {
		panic(err)
	}

	v, err := i.Eval("foo.Bar")
	if err != nil {
		panic(err)
	}

	bar := v.Interface().(func(*Data) string)

	r := bar(&d)
	println(r)
}`
