### ISSUE TITLE
The line number of the code is incorrect while panic

### ISSUE THREAD

**Issue by leonxiong516** [traefik/yaegi#546]
The following program `sample.go` triggers a panic:

```go
package main

import "fmt"

func testPanic2() {
	var m []int
	m[0] = 1
}

func testPanic() {
	testPanic2()
}

func main() {
	fmt.Println("hello")
	fmt.Println("hello")
	fmt.Println("hello")
	testPanic()
}
```

Expected result:
```console
$ go run ./sample.go
hello
hello
hello
7:6: panic
11:2: panic
18:2: panic
Exit:  reflect: slice index out of range
```

Got:
```console
$ yaegi ./sample.go
hello
hello
hello
6:6: panic
11:2: panic
15:2: panic
Exit:  reflect: slice index out of range
```

**Comment by mpl** [comment]
At first I thought it was just an off by one error, but it's more annoying than that. The error line is on the problematic node, in this case the node for "n". And instead of being on the problematic operation on this node, it is on the line where this node is declared.
