### ISSUE TITLE
cgo support?

### ISSUE THREAD

**Issue by Julio-Guerra** [traefik/yaegi#780]
#### Proposal

I guess CGO isn't supported as it is based on compile-time code generation and low-level Go ABI things, but as I couldn't clearly find the answer, I thought it would be worth asking.

#### Background

Given Traefik plugins are now based on Yaegi, advanced middleware plugins such as [web-app firewalls](https://github.com/sqreen/go-libsqreen/tree/master/waf) may be Go wrappers of C libraries.

Some of our users would like to have us in their Traefik proxy but, afaik, being limited to pure Go makes it impossible for now.

**Comment by mvertes** [comment]
As stated in the [README](https://github.com/containous/yaegi/blob/master/README.md#limitations), using CGO at interpreter level is not supported. It is always possible to wrap a pre-compiled package and export it to the interpreter by `Use` method (as it is done for the standard library), but that implies adding a new dependency to the host binary (in the plugin case, traefik).
