### ISSUE TITLE
provide a homebrew-tap recipe

### ISSUE THREAD

**Issue by kamilsk** [traefik/yaegi#785]
Hi!

#### Proposal

Do you have any plans to provide a homebrew-tap recipe? I saw you have integration with goreleaser, it provides that possibility.
For example, golangci-lint does that: https://github.com/golangci/golangci-lint/blob/6a689074bf17fd4ae1db779a74dba821a162b6c8/.goreleaser.yml#L82-L97

#### Background

It will be great to have the easiest way to install the binary on a local machine.

#### Workarounds

Now I used go mod to fetch new release and build a binary.

**Comment by mvertes** [comment]
Thanks for your proposal. We would happily get a pull request to provide a solution as you mentioned. Would you agree to submit one ?

**Comment by kamilsk** [comment]
Yes, sure.

**Comment by kamilsk** [comment]
submit is here #786

**Comment by ldez** [comment]
Closed by #786
