### ISSUE TITLE
Panic when calling ioutil.ReadAll with incorrect type

### ISSUE THREAD

**Issue by lpintes** [traefik/yaegi#860]
I accidentally called ioutil.ReadAll with a string. Just thought that a path is expected.

Then tried to call it with an int for example, it panicked again.

**Comment by mpl** [comment]
@lpintes Can you please follow the template and provide use with small reproducible examples?

**Comment by lpintes** [comment]
Sorry perhaps a stupid question, but where is the template you are talking about?
Anyway here are steps to reproduce:

Run yaegi and type the following commands:

```go
import "io/ioutil"
ioutil.ReadAll(1)
```
