### ISSUE TITLE
go.mod: module declares its path as: github.com/traefik/yaegi but was required as: github.com/containous/yaegi

### ISSUE THREAD

**Issue by servusDei2018** [traefik/yaegi#878]
![screenshot](https://user-images.githubusercontent.com/37554478/94639301-f3ec2480-02a9-11eb-9122-192f489a8552.png)

Running the following (example) code in the results in an error:

```go
package main

import "github.com/traefik/yaegi/interp"

const src = `package foo
func Bar(s string) string { return s + "-Foo" }`

func main() {
	i := interp.New(interp.Options{})

	_, err := i.Eval(src)
	if err != nil {
		panic(err)
	}

	v, err := i.Eval("foo.Bar")
	if err != nil {
		panic(err)
	}

	bar := v.Interface().(func(string) string)

	r := bar("Kung")
	println(r)
}
```

Expected result:
```console
Kung-Foo
```

Got:
```console
finding module for package github.com/containous/yaegi/interp
downloading github.com/containous/yaegi v0.9.1
found github.com/containous/yaegi/interp in github.com/containous/yaegi v0.9.1
github.com/containous/yaegi/interp: github.com/containous/yaegi@v0.9.1: parsing go.mod:
	module declares its path as: github.com/traefik/yaegi
	        but was required as: github.com/containous/yaegi
```

**Comment by mpl** [comment]
Hello,

The renaming of the namespace on the Go playground has been corrected today: https://github.com/traefik/yaegi/pull/877
As for running your example locally, no problem here with an up to date version of yaegi.
Can you please confirm that we can close this issue?

**Comment by servusDei2018** [comment]
@mpl yes thank you, it works now : )

![Screenshot_2020-09-30 The Go Playground](https://user-images.githubusercontent.com/37554478/94709991-58dc6480-0314-11eb-85ae-6efbeb357d27.png)
