### ISSUE TITLE
Eval multiple files for a single package

### ISSUE THREAD

**Issue by floren** [traefik/yaegi#882]
#### Proposal

For organizational purposes, it would be nice to be able to split my yaegi code across multiple files, which I can then Eval for invocation, something like this:

```
	_, err = i.EvalPaths("a.go", "b.go", "c.go")
	if err != nil {
		panic(err)
	}

	_, err = i.Eval(`foo.Bar()`)
	if err != nil {
		panic(err)
	}
```

You can currently call EvalPath repeatedly, but *order matters*. Thus if a function in file `a.go` calls a function defined in `b.go`, you must `EvalPath("b.go")` *first*.

#### Background

This would make organization a lot simpler, rather than dumping everything into a single file.

Also, the example given in the README doesn't even work, presumably for a related reason:

```
john@thufir:~/hacking/yaegi$ yaegi run cmd/yaegi/yaegi.go 
cmd/yaegi/yaegi.go:115:9: undefined: extractCmd
run: cmd/yaegi/yaegi.go:115:9: undefined: extractCmd
```

#### Workarounds

Call EvalPath repeatedly, but the order in which you call is critical, and incautiously-defined code could be impossible to load (code in file a.go refers to something in b.go, but something in b.go refers to a definition in a.go)

**Comment by mpl** [comment]
> #### Proposal
> For organizational purposes, it would be nice to be able to split my yaegi code across multiple files, which I can then Eval for invocation, something like this:
> 
> ```
> 	_, err = i.EvalPaths("a.go", "b.go", "c.go")
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	_, err = i.Eval(`foo.Bar()`)
> 	if err != nil {
> 		panic(err)
> 	}
> ```
> 
> You can currently call EvalPath repeatedly, but _order matters_. Thus if a function in file `a.go` calls a function defined in `b.go`, you must `EvalPath("b.go")` _first_.

The recommended solution is to move all your go files into the same directory, and to then EvalPath on the directory, like so:

```
_, err := i.EvalPath("/path/to/dir")
```

Does that not work for you?

> 
> #### Background
> This would make organization a lot simpler, rather than dumping everything into a single file.
> 
> Also, the example given in the README doesn't even work, presumably for a related reason:
> 
> ```
> john@thufir:~/hacking/yaegi$ yaegi run cmd/yaegi/yaegi.go 
> cmd/yaegi/yaegi.go:115:9: undefined: extractCmd
> run: cmd/yaegi/yaegi.go:115:9: undefined: extractCmd
> ```

Yes, that should be fixed to be instead:
```
yaegi run -syscall -unrestricted -unsafe ./cmd/yaegi
```
That said, we are aware even that the above won't work at the moment because the Panic symbol is missing. We are working on it, and we'll fix the README while we're at it.

> #### Workarounds
> Call EvalPath repeatedly, but the order in which you call is critical, and incautiously-defined code could be impossible to load (code in file a.go refers to something in b.go, but something in b.go refers to a definition in a.go)

**Comment by floren** [comment]
> The recommended solution is to move all your go files into the same directory, and to then EvalPath on the directory, like so:
> 
> ```
> _, err := i.EvalPath("/path/to/dir")
> ```
> 
> Does that not work for you?
> 

I created `/tmp/foo` and put the following files in it:

a.go:
```
package foo

import (
	"fmt"
)

func Foo() {
	fmt.Println(hello())
}
```

b.go:
```
package foo

func hello() string {
	return "hello world"
}
```

I then created /tmp/yaeg.go:

```
package main

import (
	"log"

	"github.com/traefik/yaegi/interp"
)

func main() {
	i := interp.New(interp.Options{})

	_, err := i.EvalPath("/tmp/foo")
	if err != nil {
		log.Fatalf("EvalPath failed: %v", err)
	}

	_, err = i.Eval("foo.Foo()")
	if err != nil {
		log.Fatalf("Eval failed: %v", err)
	}
}
```

And ran it:

```
john@thufir:~$ go run /tmp/yaeg.go 
2020/10/01 11:11:08 EvalPath failed: package location /home/john not in GOPATH
exit status 1
```

**Comment by mpl** [comment]
The interpreter needs to work in a GoPath. So you need to either set it in the options when you instantiate the interpreter, or move your code to GOPATH, like so:

```
mkdir -p $GOPATH/src/floren
mv /tmp/foo $GOPATH/src/floren/foo
mv /tmp/foo/yaeg.go $GOPATH/src/floren/yaeg.go
```

Then, rewrite yaeg.go like this:

```
package main

import (
	"log"

	"github.com/containous/yaegi/stdlib"
	"github.com/traefik/yaegi/interp"
)

func main() {
	i := interp.New(interp.Options{})

	i.Use(stdlib.Symbols)
	_, err := i.EvalPath("./foo")
	if err != nil {
		log.Fatalf("EvalPath failed: %v", err)
	}

	if _, err := i.Eval(`import "./foo"`); err != nil {
		log.Fatal(err)
	}
	if _, err := i.Eval("foo.Foo()"); err != nil {
		log.Fatal(err)
	}
}
```

And finally, `yaegi run ./yaeg.go`

**Comment by floren** [comment]
With some messing around, I got it to work in a way that'll suit my purposes. I structured my code like this:

```
/tmp/bundle
	src/
		main/		
			main.go
		foo/	
			a.go
			b.go
```

In the above, main.go imports package foo and, in a function called Main(), executes a function from the library.

I used this to load and execute my code:

```
	package main
	
	import (
		"log"
	
		"github.com/traefik/yaegi/interp"
		"github.com/traefik/yaegi/stdlib"
	)
	
	func main() {
		i := interp.New(interp.Options{GoPath: "/tmp/bundle"})
	
		i.Use(stdlib.Symbols)
	
		_, err := i.Eval(`import "main"`)
		if err != nil {
			log.Fatalf("EvalPath failed: %v", err)
		}
	
		_, err = i.Eval("main.Main()")
		if err != nil {
			log.Fatalf("Eval failed: %v", err)
		}
	}
```

I think this accomplishes what I need, so I'll close the issue. Thank you.
