### ISSUE TITLE
Append to the imported struct field cause a panic

### ISSUE THREAD

**Issue by LopatkinEvgeniy** [traefik/yaegi#888]
The following program `sample.go` triggers a panic:

If there is an imported struct in a script that has a slice field - you can't append to that slice because it causes a panic

```go
package main

import (
	"fmt"
	"reflect"

	"github.com/traefik/yaegi/interp"
)

type BarParams struct {
	Arr []string
}

const script = `
package bar

import "foo"

func Bar(p foo.BarParams) string {
	p.Arr = append(p.Arr, "4")
	return "ok"
}
`

func main() {
	i := interp.New(interp.Options{})

	custom := make(map[string]map[string]reflect.Value)
	custom["foo"] = make(map[string]reflect.Value)
	custom["foo"]["BarParams"] = reflect.ValueOf((*BarParams)(nil))
	i.Use(custom)

	_, err := i.Eval(script)
	handle(err)

	v, err := i.Eval("bar.Bar")
	handle(err)

	bar := v.Interface().(func(BarParams) string)

	result := bar(BarParams{Arr: []string{"1", "2", "3"}})
	fmt.Println(result)
}

func handle(err error) {
	if err != nil {
		panic(err)
	}
}
```

Expected result:
```console
ok
```

Got:
```console
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
main.handle(...)
	/home/evgen/go/src/elopatkin/main.go:47
main.main()
	/home/evgen/go/src/elopatkin/main.go:34 +0x4cd
exit status 2
```

---

Also slice fields can't be used with a spread operator. Change the script from prev example:
```go
const script = `
package bar

import "foo"

func Bar(p foo.BarParams) string {
	_ = append([]string{}, p.Arr...)
	return "ok"
}
`
``` 

Got:
```console
7:13: panic
panic: reflect.Set: value of type []string is not assignable to type string [recovered]
	panic: reflect.Set: value of type []string is not assignable to type string

goroutine 1 [running]:
elopatkin/vendor/github.com/traefik/yaegi/interp.runCfg.func1(0xc000112460, 0xc000119900)
	/home/evgen/go/src/elopatkin/vendor/github.com/traefik/yaegi/interp/run.go:124 +0x20c
panic(0x670a80, 0xc000010bc0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
reflect.Value.assignTo(0x66d620, 0xc00000c880, 0x197, 0x6ced8b, 0xb, 0x670a80, 0x0, 0x97, 0xc00000c940, 0x66d620)
	/usr/local/go/src/reflect/value.go:2403 +0x426
reflect.Value.Set(0x670a80, 0xc000010bb0, 0x198, 0x66d620, 0xc00000c880, 0x197)
	/usr/local/go/src/reflect/value.go:1532 +0xbd
reflect.Append(0x66d620, 0xc00000c8a0, 0x197, 0xc000149a70, 0x1, 0x1, 0x66d620, 0xc00000c880, 0x197)
	/usr/local/go/src/reflect/value.go:2028 +0xe8
elopatkin/vendor/github.com/traefik/yaegi/interp._append.func2(0xc000112460, 0xc00005ecc0)
	/home/evgen/go/src/elopatkin/vendor/github.com/traefik/yaegi/interp/run.go:2469 +0x14c
elopatkin/vendor/github.com/traefik/yaegi/interp.runCfg(0xc000119900, 0xc000112460)
	/home/evgen/go/src/elopatkin/vendor/github.com/traefik/yaegi/interp/run.go:130 +0x6d
elopatkin/vendor/github.com/traefik/yaegi/interp.genFunctionWrapper.func2.1(0xc00000c840, 0x1, 0x1, 0xc00000c840, 0xc00005f050, 0x13)
	/home/evgen/go/src/elopatkin/vendor/github.com/traefik/yaegi/interp/run.go:716 +0x3cb
reflect.callReflect(0xc00005f050, 0xc000149dc8, 0xc000149db0)
	/usr/local/go/src/reflect/value.go:549 +0x322
reflect.makeFuncStub(0xc00005f080, 0x3, 0x3, 0x1, 0x67a120, 0xc00005f050, 0x67a120, 0xc00005f050, 0x13, 0x0, ...)
	/usr/local/go/src/reflect/asm_amd64.s:20 +0x42
main.main()
	/home/evgen/go/src/elopatkin/main.go:41 +0x3a9
exit status 2
```

**Comment by mpl** [comment]
I don't know yet what exactly you're doing wrong, but I don't believe that a yaegi bug is involved for now, as one can successfully do something equivalent, such as:

```
package main

import (
	"fmt"
	"log"

	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
)

const fooSrc = `package foo

type BarParams struct {
	Arr []string
}
`

const barSrc = `package bar

import (
	"fmt"
	"foo"
)

func Bar(p *foo.BarParams) string {
	p.Arr = append(p.Arr, "4")
	return "ok"
}
`

func main() {
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	if _, err := i.Eval(fooSrc); err != nil {
		log.Fatal(err)
	}
	// fmt.Println(i.Symbols("foo"))

	if _, err := i.Eval(barSrc); err != nil {
		log.Fatal(err)
	}

	v, err := i.Eval(`bar.Bar`)
	if err != nil {
		log.Fatal(err)
	}

	bar := v.Interface().(func(*struct { Arr []string }) string)

	result := bar(&struct { Arr []string }{Arr: []string{"1", "2", "3"}})
	fmt.Println(result)
}
```

**Comment by LopatkinEvgeniy** [comment]
In my example i export a BarParams struct from the golang code. That is a difference. To reproduce you must declare some struct with a slice field and then import it inside yaegi script using a `Use` method. Then append something to that slice field inside yaegi.

**Comment by mpl** [comment]
> In my example i export a BarParams struct from the golang code. That is a difference. To reproduce you must declare some struct with a slice field in your golang code and then import it inside yaegi script using a `Use` method. Then append something to that slice field inside yaegi.
> 
> Not
> 
> ```go
> _, err := i.Eval(stringWithBarDefinition)
> ```
> 
> But
> 
> ```go
> custom["foo"]["BarParams"] = reflect.ValueOf((*BarParams)(nil))
> i.Use(custom)
> ```

Sure, but that's what I meant: i'm not yet convinced that what you're doing here is enough/correct/supported etc. It might not be enough to just manually add foo.BarParams as you did to the symbols before you can use it. It might be the wrong scope, etc. I don't know yet.

**Comment by mpl** [comment]
Alright, just to confirm that it can be done, here's a working example closer to what you were trying to achieve:

```go
package main

import (
	"fmt"
	"log"
	"reflect"

	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
)

var Bar string

const barSrc = `package bar

import (
	"foo"
)

func Bar() string {
	foo.Bar = "Hello"
	return foo.Bar
}
`

func main() {
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	exports := interp.Exports{"foo": map[string]reflect.Value{"Bar": reflect.ValueOf(&Bar).Elem()}}
	i.Use(exports)

	if _, err := i.Eval(barSrc); err != nil {
		log.Fatal(err)
	}

	v, err := i.Eval(`bar.Bar`)
	if err != nil {
		log.Fatal(err)
	}

	bar := v.Interface().(func() string)
	result := bar()
	fmt.Println(result)
}
```

So we're marking that bug as a question for now. That said:

1) We acknowledge that it is a pain to achieve, and we're going to work on an easier way to do it. Specifically, something that will probably replace that part:

```
	exports := interp.Exports{"foo": map[string]reflect.Value{"Bar": reflect.ValueOf(&Bar).Elem()}}
	i.Use(exports)
```

2) We acknowledge there might be bugs for more complicated cases such as yours (e.g. with types, and composite literals, etc), and we'll investigate them while we're doing 1) (or after it's done).

**Comment by LopatkinEvgeniy** [comment]
Sorry, but i can't understand your prev. example. It do something different.

To reproduce a bug you should specify struct in your golang code and then `Use` it in you yaegi code. This struct must contain a slice field. When you append to this slice inside yaegi a panic will cause. 

Yaegi has an API to import golang functions and structs, but it has a bug. In your example there are no:
* struct inporting
* slice field appending

So it is completely wrong. And bug still exist.

**Comment by mpl** [comment]
> Sorry, but i can't understand your prev. example. It do something different.

Yes it does, we never claimed it was identical.

> To reproduce a bug you should specify struct in your golang code and then `Use` it in you yaegi code. This struct must contain a slice field. When you append to this slice inside yaegi a panic will cause.

And I will reiterate that I am not yet convinced that you are properly "importing" your BarParams type into the symbols of yaegi, which would be the reason why you are seeing this bug.
And which is why we said in my previous reply that we are going to work on a way to facilitate that and to make sure it is done properly.

> Yaegi has an API to import golang functions and structs, but it has a bug. In your example there are no:
> 
> * struct importing
> * slice field appending

Yes, I know.

> So your previous example is completely wrong.

No, it is not wrong, it is correct, but it is different.

> And a bug still exists.

Maybe. We already acknowledged that in the previous message.
