### ISSUE TITLE
Can't import internal library "os/exec" (from version >= 0.8.12): 'unable to find source related to: "os/exec"'

### ISSUE THREAD

**Issue by g3rzi** [traefik/yaegi#901]
The following program `sample.go` triggers a panic:

```go
package main
import (
	"github.com/containous/yaegi/interp"
	"github.com/containous/yaegi/stdlib"
)

var payload = `

package main

import (
	"fmt"
	"os/exec"
)

func main() {
    
	cmd := exec.Command("ls")
	fmt.Println(cmd)
	fmt.Println("Hello, playground")
}

`
func main(){

	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	_, err := i.Eval(payload)
	if err != nil {
		panic(err)
	}
}
```

Expected result:
```console
$ go run ./sample.go
/bin/ls
Hello, playground
```

Got:
```console
GOROOT=/usr/local/go #gosetup
GOPATH=/home/jiren/go #gosetup
/usr/local/go/bin/go build -o /tmp/___go_build_main_go__3_ /home/jiren/go/src/mytest/main.go #gosetup
/tmp/___go_build_main_go__3_ #gosetup
panic: 7:2: import "os/exec" error: unable to find source related to: "os/exec"

goroutine 1 [running]:
main.main()
        /home/jiren/go/src/mytest/main.go:38 +0xbb

Process finished with exit code 2

```

The problem exist from versions `v0.8.12` and above (I checked all the versions until `0.9.2`), in everyone the problem exist.  
But it doesn't happen on version `v0.8.11` and below.  
I am using `go.mod` and I tested the versions by changing from:  
`github.com/containous/yaegi v0.8.11` (work) to `github.com/containous/yaegi v0.8.12` (doesn't work).  

Any idea how to solve it in higher versions? Maybe I my settings are incorrect?

**Comment by mvertes** [comment]
As yaegi may be embedded in some servers or long running processes, some symbols from stdlib are potentially dangerous, mainly the function that can exit the host executable, or escape the sandbox. `os.Exec` is one of them. We have isolated those symbols from stdlib and syscall in `github.com/traefik/yaegi/stdlib/unrestricted`, which you need to import, and call `i.Use` on.

The following works:
```go
package main

import (
    "github.com/traefik/yaegi/interp"
    "github.com/traefik/yaegi/stdlib"
    "github.com/traefik/yaegi/stdlib/unrestricted"
)

var payload = `

package main

import (
 "fmt"
  "os/exec"
)

func main() {
    cmd := exec.Command("ls")
    fmt.Println(cmd)
    fmt.Println("Hello, playground")
}
`

func main() {

    i := interp.New(interp.Options{})
    i.Use(stdlib.Symbols)
    i.Use(unrestricted.Symbols)

    _, err := i.Eval(payload)
    if err != nil {
        panic(err)
    }
}
```

**Comment by g3rzi** [comment]
Great, it works. thank you very much for your quick response and this awesome project :)
