### ISSUE TITLE
compiteGenerator not implemented for type kind: slice

### ISSUE THREAD

**Issue by ArthurYangZhiBin** [traefik/yaegi#976]
_, err = i.Eval(fmt.Sprintf(import "%s", manifest.Import))

err:/golang.org/x/crypto/ocsp/ocsp.go:142:32: compiteGenerator not implemented for type kind: slice

ocsp.go:142:32:
var (
	oidSignatureMD2WithRSA      = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 2}
)

**Comment by mvertes** [comment]
`import "golang.org/x/crypto/ocsp"` now works ok (yaegi-0.15.0).
