### ISSUE TITLE
Constant definition loop with protoreflect

### ISSUE THREAD

**Issue by katallaxie** [traefik/yaegi#995]
The following library [protoreflect](https://github.com/protocolbuffers/protobuf-go/blob/master/reflect/protoreflect/methods.go) triggers a panic.

It creates the following panic.

```bash
google.golang.org/protobuf/reflect/protoreflect/methods.go:18:2: constant definition loop
```

**Comment by mvertes** [comment]
also related to #260

**Comment by katallaxie** [comment]
@mvertes With #1001 the error has changed.

```bash
vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe.go:48:9: panic
vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe.go:42:16: panic
```

It seems that the `EnumNumber` https://github.com/protocolbuffers/protobuf-go/blob/160c7477e0e899d5072bb25635f46053df619fbf/reflect/protoreflect/value_unsafe.go#L42 is not imported.

**Comment by mvertes** [comment]
Sorry for being so late.

The fix here is to use the pure go version of the package. This is done by using yaegi tags with the build tags as in https://github.com/protocolbuffers/protobuf-go/blob/160c7477e0e899d5072bb25635f46053df619fbf/reflect/protoreflect/value_pure.go#L5.

I tested the following with yaegi-v0.12.0 and it works (at least the import):

sample.go:
```go
package main

// yaegi:tags purego appengine

import ( 
    _ "google.golang.org/protobuf/reflect/protoreflect"
)

func main() {
    println("ok")
}
```

and then:
```console
$ yaegi ./sample.go
ok
```
